name: Check Secrets

on:
  push: # Triggers the workflow when code is pushed to the repository
    branches:
      - main
      - develop
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    environment: ESTIMATE_ENV_VARIABLES # Specify the environment where secrets are stored

    steps:
      - name: Check if secret is set
        env:
          MY_SECRET_1: ${{ secrets.DATABASE_URL }} # Access secret from the environment
          MY_SECRET_2: ${{ secrets.STRIPE_SECRET_KEY }} # Access secret from the environment
        run: |
          echo "DATABASE_URL: $MY_SECRET_1" | sed 's/./& /g'
          echo "STRIPE_SECRET_KEY: $MY_SECRET_2" | sed 's/./& /g'